In [1]:
import polars as pl
import httpx
from dotenv import load_dotenv
import os

load_dotenv()

PURPLE_AIR_API_KEY = os.getenv("PURPLE_AIR_API_KEY")

In [2]:
# get json data from purple air response - note this code is from httpx documentation and just modified to work with this project's usecase

try:
    sensors = httpx.get(
        "https://api.purpleair.com/v1/sensors",
        params={
            "api_key": PURPLE_AIR_API_KEY,
            "fields": "latitude,longitude,position_rating,location_type,last_seen",
            "max_age": 0,
            "nwlat": 40.962891,
            "nwlng": -74.264395,
            "selat": 40.470116,
            "selng": -73.675450,
        },
    )
    if sensors.status_code == 200:
        sensors_json = sensors.json()
        print(sensors_json)
    else:
        print(f"Request failed with status code: {sensors.status_code}, response: {sensors.text}")
except httpx.HTTPStatusError as e:
    print(f"HTTP error occurred: {e.response.status_code} - {e.response.text}")
except httpx.RequestError as e:
    print(f"An error occurred while trying to make the request: {e}")

{'api_version': 'V1.2.0-1.1.45', 'time_stamp': 1774201740, 'data_time_stamp': 1774201710, 'max_age': 0, 'firmware_default_version': '7.02', 'fields': ['sensor_index', 'last_seen', 'location_type', 'position_rating', 'latitude', 'longitude'], 'location_types': ['outside', 'inside'], 'data': [[262999, 1774201640, 1, 0, 40.801434, -73.970535], [263287, 1755525360, 1, 5, 40.842293, -74.07955], [263301, 1755525237, 1, 5, 40.842327, -74.079544], [263457, 1755525786, 1, 5, 40.84218, -74.07933], [1660, 1663947634, 0, 5, 40.721, -74.1928], [2319, 1666785882, 0, 5, 40.809963, -73.95416], [264499, 1762224167, 1, 5, 40.716164, -73.96324], [2897, 1518323822, 0, 5, 40.790447, -73.733284], [265475, 1774147551, 1, 0, 40.682373, -73.97324], [265803, 1773728621, 0, 0, 40.686188, -73.94205], [4803, 1774201661, 0, 5, 40.787937, -73.96807], [5100, 1511917657, 1, 0, 40.734493, -73.8193], [5110, 1511921460, 1, 0, 40.735878, -73.85171], [5444, 1533082789, 0, 0, 40.844254, -73.98846], [5476, 1527782528, 1, 5, 40.844254, -73.98846], [5648, 1555619294, 0, 5, 40.735424, -74.00946], [269164, 1774201664, 1, 0, 40.656296, -73.958176], [8472, 1587682905, 0, 0, 40.91503, -73.850105], [8524, 1546539618, 1, 5, 40.708485, -74.003006], [8634, 1565027730, 0, 5, 40.790398, -73.73332], [271321, 1774201605, 0, 5, 40.57837, -74.2196], [271391, 1774201650, 0, 5, 40.515587, -74.26245], [11308, 1709925666, 0, 4, 40.70923, -74.19507], [12391, 1774201691, 1, 5, 40.809536, -73.9301], [276266, 1774201605, 0, 5, 40.666515, -73.95539], [276498, 1774201710, 1, 0, 40.773827, -73.98049], [14515, 1534199362, 0, 0, 40.73226, -73.99178], [14931, 1552592039, 0, 0, 40.735386, -73.99667], [278505, 1751083008, 1, 0, 40.778328, -73.96366], [18011, 1656523616, 0, 5, 40.663353, -74.23628], [281206, 1774201642, 1, 0, 40.794575, -73.77996], [281410, 1774201595, 0, 0, 40.95255, -73.75448], [281452, 1774201690, 1, 0, 40.906597, -73.80521], [21441, 1648421966, 0, 5, 40.77256, -73.95144], [21605, 1659817651, 0, 0, 40.7324, -74.141754], [21745, 1680379489, 0, 1, 40.769547, -74.16863], [284144, 1774201647, 0, 0, 40.719227, -74.0478], [22711, 1561119713, 0, 0, 40.814545, -73.95115], [22749, 1774201645, 0, 5, 40.74699, -74.0259], [284972, 1774201632, 0, 5, 40.713257, -73.97851], [22869, 1774201595, 1, 5, 40.81531, -73.950325], [22877, 1657201385, 0, 5, 40.814503, -73.951454], [23359, 1716276919, 1, 5, 40.67557, -73.974915], [285560, 1774201616, 0, 0, 40.756435, -73.82577], [285972, 1774201631, 0, 0, 40.93026, -74.036095], [24311, 1774201661, 0, 5, 40.7117, -73.84475], [25031, 1602777624, 1, 5, 40.74355, -73.99596], [25675, 1774201706, 1, 5, 40.75028, -73.72096], [287862, 1774201646, 0, 0, 40.821, -73.949], [25885, 1578407347, 1, 5, 40.695396, -73.94181], [288406, 1774201641, 0, 3, 40.68475, -73.97376], [26543, 1635246350, 0, 5, 40.727627, -73.95822], [26867, 1704902822, 1, 4, 40.92596, -73.75886], [26885, 1581350375, 1, 5, 40.735474, -74.006714], [289320, 1774201709, 0, 0, 40.726334, -73.94194], [290360, 1774201668, 0, 0, 40.734013, -73.93703], [28225, 1601298113, 1, 5, 40.742565, -73.95947], [28227, 1578969461, 1, 5, 40.748177, -74.00493], [28285, 1774201606, 0, 5, 40.736893, -74.04125], [290906, 1774201591, 0, 0, 40.62045, -74.04003], [29183, 1774201678, 0, 5, 40.763924, -73.98655], [29357, 1577201830, 0, 0, 40.650017, -74.18334], [29365, 1597443606, 0, 5, 40.64674, -74.21431], [30519, 1561481387, 0, 5, 40.7192, -73.95298], [30541, 1595205912, 0, 5, 40.73445, -73.95528], [30623, 1593361740, 0, 5, 40.723843, -73.93848], [30655, 1630550347, 0, 5, 40.71462, -73.95475], [31565, 1608882212, 0, 5, 40.80931, -73.960045], [31591, 1608883079, 0, 5, 40.80514, -73.96407], [293913, 1774201633, 0, 0, 40.744663, -73.883766], [31841, 1590088173, 1, 0, 40.748127, -73.97441], [32293, 1620687594, 1, 5, 40.93328, -73.76289], [32581, 1658029518, 0, 5, 40.74332, -73.99613], [295845, 1774201708, 0, 5, 40.751877, -73.8841], [33745, 1714068535, 0, 5, 40.7274, -73.94428], [34273, 1563980021, 1, 0, 40.66689, -73.957565], [34337, 1596392407, 0, 5, 40.712654, -73.68148], [35015, 1612202197, 0, 5, 40.727356, -73.94473], [35785, 1572012422, 1, 5, 40.78126, -73.95542], [37051, 1646226493, 0, 5, 40.726143, -73.95065], [37185, 1774201622, 0, 5, 40.705246, -73.9394], [37569, 1603036484, 1, 5, 40.771885, -73.99003], [37965, 1614878481, 0, 1, 40.68439, -73.933815], [301485, 1774201605, 0, 5, 40.746037, -73.865074], [301487, 1774201610, 0, 5, 40.750484, -73.828606], [301601, 1774201624, 0, 0, 40.713326, -73.95635], [40217, 1634922227, 0, 5, 40.781563, -73.95483], [302500, 1774201662, 1, 0, 40.65654, -73.98387], [40469, 1629601142, 0, 5, 40.78126, -73.95542], [302874, 1774201592, 1, 0, 40.953445, -74.20641], [303492, 1774201670, 1, 0, 40.721706, -73.842545], [41963, 1574805063, 0, 0, 40.682747, -73.982376], [305198, 1770915720, 0, 0, 40.743214, -74.00218], [305438, 1774201679, 0, 5, 40.78137, -73.955086], [43527, 1774201629, 1, 5, 40.79454, -73.9666], [46755, 1774201607, 1, 5, 40.75822, -73.95885], [47243, 1645471271, 1, 3, 40.750286, -74.04257], [47391, 1597709104, 1, 0, 40.934433, -73.76366], [47699, 1774201641, 0, 5, 40.88606, -74.073456], [49363, 1750804173, 1, 5, 40.73014, -73.95654], [50493, 1587945250, 0, 5, 40.68223, -73.994225], [51537, 1591197709, 0, 5, 40.754417, -73.99487], [52789, 1616001714, 0, 0, 40.64674, -74.21431], [53443, 1671556054, 0, 5, 40.800728, -74.2435], [55319, 1661715589, 1, 0, 40.848957, -73.93108], [55347, 1596370560, 1, 5, 40.81046, -73.96442], [55511, 1719084816, 0, 5, 40.64454, -74.22246], [55547, 1774146543, 1, 5, 40.665787, -74.199875], [55689, 1774201686, 1, 5, 40.691795, -73.9936], [56057, 1608158638, 0, 5, 40.663548, -74.2088], [56155, 1629607219, 0, 5, 40.645157, -74.081635], [56295, 1688411019, 1, 5, 40.654358, -74.202324], [56329, 1591556100, 1, 5, 40.66357, -74.20901], [56541, 1774201708, 1, 5, 40.81707, -73.95817], [56559, 1631127881, 1, 5, 40.593803, -73.985756], [56561, 1710776749, 1, 0, 40.709435, -73.798325], [56563, 1595866568, 1, 5, 40.671658, -73.76745], [56579, 1655520448, 0, 5, 40.502357, -74.24064], [56593, 1760489585, 1, 5, 40.81687, -73.95785], [57585, 1671986157, 1, 5, 40.704773, -73.94186], [58069, 1724238701, 0, 5, 40.754402, -73.99486], [58657, 1648844078, 0, 5, 40.848892, -73.930756], [58729, 1593729258, 1, 0, 40.645294, -74.08159], [58739, 1596245561, 1, 5, 40.89549, -73.82867], [58749, 1637082720, 1, 5, 40.863415, -73.927246], [58843, 1633623429, 0, 5, 40.59366, -73.98591], [58847, 1596245579, 1, 5, 40.895718, -73.82853], [58867, 1623681574, 0, 5, 40.848824, -73.93068], [60137, 1604862673, 0, 5, 40.771294, -73.91327], [60863, 1692454359, 0, 5, 40.77311, -73.98817], [60865, 1596648869, 0, 0, 40.73663, -73.82167], [66907, 1734358540, 1, 5, 40.63479, -73.94941], [68313, 1774201693, 0, 5, 40.82101, -74.20403], [75131, 1774201650, 1, 5, 40.7411, -73.992455], [75605, 1710785941, 1, 5, 40.78518, -74.239944], [75669, 1735330347, 1, 0, 40.7956, -74.23374], [75951, 1759351755, 1, 0, 40.794285, -74.23389], [75971, 1774201608, 1, 0, 40.80728, -74.20113], [77063, 1774201698, 1, 5, 40.66419, -73.97855], [77201, 1774201669, 1, 0, 40.713867, -73.989525], [77731, 1701297734, 1, 5, 40.841682, -73.92522], [77735, 1774201608, 1, 3, 40.860535, -73.8858], [77747, 1644129063, 1, 5, 40.85821, -73.888985], [77755, 1696945244, 1, 5, 40.83029, -73.92193], [77771, 1743706279, 1, 5, 40.79208, -73.94781], [78071, 1637011711, 0, 0, 40.78581, -74.238235], [81785, 1774201620, 0, 5, 40.695778, -73.99408], [81845, 1614355095, 0, 5, 40.83405, -73.90247], [82031, 1774201650, 1, 3, 40.775803, -73.980644], [82467, 1619542399, 1, 5, 40.833984, -73.90275], [82667, 1774201646, 1, 5, 40.777107, -73.98871], [82929, 1774201657, 1, 5, 40.81568, -73.96087], [86845, 1673302484, 1, 5, 40.723686, -73.99994], [87083, 1686782929, 0, 5, 40.71082, -73.96461], [87557, 1774201647, 0, 5, 40.77808, -73.91492], [87629, 1774201621, 1, 5, 40.68766, -73.967545], [87841, 1660737882, 1, 5, 40.79356, -73.93863], [88305, 1692716265, 1, 5, 40.861053, -73.89137], [88439, 1774201661, 0, 5, 40.721226, -73.97974], [89311, 1646429980, 1, 0, 40.735733, -73.98689], [89409, 1774201684, 1, 5, 40.70325, -73.98952], [89713, 1614836811, 1, 5, 40.85809, -73.89222], [89929, 1677581751, 0, 5, 40.815376, -73.888435], [89957, 1774201651, 0, 5, 40.792336, -73.94736], [90145, 1774201600, 0, 5, 40.8008, -74.24332], [90165, 1686844616, 0, 5, 40.695248, -73.97049], [90247, 1774201669, 1, 5, 40.567776, -74.1157], [90249, 1774201636, 0, 3, 40.861225, -73.89016], [90269, 1754321311, 0, 5, 40.858074, -73.88898], [90283, 1774124331, 0, 5, 40.81536, -73.888374], [90287, 1721743250, 1, 5, 40.688637, -73.97614], [90293, 1647013501, 0, 5, 40.82951, -73.91953], [90317, 1739307106, 1, 5, 40.815304, -73.88829], [90337, 1696620126, 0, 5, 40.689518, -73.976364], [90347, 1662564158, 0, 5, 40.815346, -73.88823], [90363, 1774201640, 1, 5, 40.83745, -73.91547], [90389, 1757920006, 0, 5, 40.83022, -73.92234], [90397, 1647448609, 0, 5, 40.860977, -73.89186], [90405, 1659718105, 0, 5, 40.77217, -73.96004], [90423, 1659719126, 1, 5, 40.772163, -73.9599], [90683, 1620827293, 0, 5, 40.670654, -73.9935], [90981, 1615162801, 1, 3, 40.86716, -73.886566], [91033, 1626648151, 0, 5, 40.856663, -73.916565], [91213, 1612970368, 0, 5, 40.804497, -73.9655], [91415, 1720449379, 0, 5, 40.792587, -73.947495], [91423, 1745864176, 0, 5, 40.861134, -73.891556], [91439, 1703020817, 1, 5, 40.688778, -73.97618], [91441, 1774201674, 0, 5, 40.56849, -74.11661], [91443, 1721158475, 0, 5, 40.793465, -73.93887], [91581, 1612970373, 0, 5, 40.804523, -73.965515], [91663, 1774201659, 1, 5, 40.568405, -74.116486], [91899, 1746113065, 0, 5, 40.83016, -73.9219], [92167, 1772804751, 0, 5, 40.79341, -73.938484], [92169, 1774201646, 0, 5, 40.837517, -73.91544], [92171, 1774201694, 0, 5, 40.860455, -73.88581], [92177, 1642246270, 0, 5, 40.792454, -73.94717], [92185, 1607123847, 0, 0, 40.811546, -73.85955], [94957, 1774201673, 0, 5, 40.663574, -74.209015], [95581, 1617037101, 1, 5, 40.742535, -74.000084], [95663, 1707158012, 1, 0, 40.81001, -73.95421], [95773, 1616168239, 1, 5, 40.771767, -73.92231], [95781, 1690766455, 1, 5, 40.792534, -73.96803], [96271, 1637461708, 1, 5, 40.809715, -73.9645], [96741, 1684239983, 0, 5, 40.663544, -74.20889], [96849, 1750632110, 1, 5, 40.664932, -74.25562], [97133, 1628457274, 0, 5, 40.713238, -73.97852], [97219, 1617047961, 0, 5, 40.68759, -74.00014], [97399, 1673302496, 0, 0, 40.67019, -73.95488], [97641, 1693914375, 0, 5, 40.65957, -73.98943], [98723, 1696180792, 0, 5, 40.745167, -74.05944], [98909, 1774201699, 0, 5, 40.70973, -74.21211], [98963, 1667142768, 0, 5, 40.70935, -74.22198], [98971, 1668737280, 0, 5, 40.70376, -74.21527], [99355, 1774201708, 0, 5, 40.71593, -74.2219], [99359, 1719883364, 0, 5, 40.72058, -74.21715], [99365, 1637161653, 0, 0, 40.721146, -74.19263], [99379, 1636733366, 0, 0, 40.72086, -74.19313], [99439, 1712240929, 0, 5, 40.70123, -74.19895], [99449, 1753980513, 0, 5, 40.71819, -74.21154], [99495, 1652661208, 1, 5, 40.807117, -73.95901], [100869, 1629366035, 0, 0, 40.711964, -73.96296], [101523, 1774201709, 1, 5, 40.71871, -73.947815], [101561, 1769823175, 0, 5, 40.72624, -73.976364], [101639, 1754932844, 0, 5, 40.713753, -73.977585], [101655, 1771628659, 0, 5, 40.7643, -73.98364], [103518, 1774201659, 1, 5, 40.782597, -73.98462], [103672, 1643659771, 1, 5, 40.708714, -74.01649], [106596, 1634652406, 0, 5, 40.72102, -74.19281], [107550, 1752034671, 1, 5, 40.650993, -73.94441], [107566, 1774201666, 1, 0, 40.780315, -73.975914], [107798, 1774201683, 1, 5, 40.650887, -73.94439], [110490, 1714055992, 0, 5, 40.71042, -74.08446], [113594, 1652141972, 0, 5, 40.72067, -73.96148], [114593, 1700510206, 0, 5, 40.7282, -74.0776], [114761, 1774201594, 1, 5, 40.78562, -73.97826], [115557, 1626986016, 1, 0, 40.816925, -73.96041], [118639, 1656454280, 0, 1, 40.72863, -74.19404], [118651, 1656434394, 0, 0, 40.699417, -74.219475], [118655, 1656435600, 0, 0, 40.711395, -74.21075], [118659, 1656453782, 0, 0, 40.73445, -74.18464], [118665, 1663947893, 0, 5, 40.72157, -74.19259], [118669, 1656452355, 0, 0, 40.70612, -74.20901], [118671, 1656430082, 0, 5, 40.707005, -74.21966], [118685, 1634311176, 1, 4, 40.697308, -73.92422], [118697, 1663947887, 0, 5, 40.721546, -74.19341], [118701, 1656432994, 0, 5, 40.706123, -74.2213], [118709, 1634311060, 1, 4, 40.697308, -73.92422], [118711, 1656428770, 0, 1, 40.707752, -74.220856], [118717, 1656452117, 0, 0, 40.708534, -74.20626], [118775, 1713366395, 0, 0, 40.713238, -73.97854], [119801, 1656452510, 0, 0, 40.734028, -74.20831], [120223, 1656433536, 0, 0, 40.70745, -74.214836], [120899, 1656454578, 0, 0, 40.742935, -74.18052], [121261, 1656450812, 0, 1, 40.733772, -74.2079], [122273, 1637461767, 0, 5, 40.809914, -73.96439], [122453, 1652141969, 1, 5, 40.72065, -73.96144], [123883, 1745702584, 1, 5, 40.723476, -73.99894], [124245, 1653314778, 0, 1, 40.704216, -73.97121], [124269, 1663166182, 0, 5, 40.69901, -73.97489], [124783, 1685801439, 1, 0, 40.707428, -74.00723], [126265, 1768334455, 0, 5, 40.677933, -73.9883], [126583, 1704891017, 1, 5, 40.735973, -73.98752], [126739, 1774201635, 1, 5, 40.72485, -74.00047], [127263, 1680198861, 0, 5, 40.674637, -73.99628], [127277, 1659800895, 1, 5, 40.795994, -73.94969], [128363, 1649367908, 1, 5, 40.785706, -73.973145], [128551, 1774201606, 1, 0, 40.75349, -73.885956], [130381, 1764174670, 1, 5, 40.71858, -74.00807], [130905, 1749673664, 1, 5, 40.693344, -73.99259], [130973, 1774201601, 1, 5, 40.8015, -73.97047], [131429, 1774201636, 0, 5, 40.720783, -74.21691], [131447, 1697213698, 0, 5, 40.72151, -74.19329], [131483, 1737398023, 0, 5, 40.764168, -74.02992], [131845, 1665681485, 0, 5, 40.699005, -73.97508], [132033, 1677263958, 0, 1, 40.69316, -73.98755], [135024, 1774201636, 1, 5, 40.8014, -73.97047], [135148, 1774201604, 0, 5, 40.910847, -73.90167], [136692, 1687787397, 0, 0, 40.635597, -73.9541], [138798, 1774201611, 1, 5, 40.65943, -73.97708], [138800, 1639178689, 1, 0, 40.74701, -73.71489], [138804, 1760365687, 1, 5, 40.58498, -73.69887], [138818, 1766794493, 1, 5, 40.666004, -73.929535], [138842, 1755964367, 1, 5, 40.68812, -73.98797], [138844, 1774201707, 0, 5, 40.646797, -73.897415], [139146, 1682603850, 1, 5, 40.851097, -73.787704], [139148, 1735332295, 1, 0, 40.8748, -73.92461], [139154, 1670614847, 1, 5, 40.76912, -73.95201], [139156, 1710527597, 1, 5, 40.84084, -73.84984], [139176, 1638565256, 1, 0, 40.743336, -73.8872], [139186, 1638565430, 1, 0, 40.839897, -73.86247], [140006, 1694109297, 1, 5, 40.654625, -73.87386], [140004, 1750957849, 1, 5, 40.821667, -73.95206], [140010, 1694181737, 1, 5, 40.612816, -73.96031], [140062, 1774201672, 1, 5, 40.874683, -73.904335], [140064, 1768000403, 1, 5, 40.87065, -73.917595], [140082, 1774201629, 1, 5, 40.75787, -74.23143], [140094, 1774201695, 1, 5, 40.8934, -73.83783], [140100, 1639008138, 1, 0, 40.87975, -73.88329], [140128, 1639181092, 1, 0, 40.774357, -73.94898], [140138, 1672880570, 1, 5, 40.721127, -73.75328], [140140, 1693227705, 1, 5, 40.66883, -73.92767], [140146, 1692838880, 1, 5, 40.67691, -73.89298], [140152, 1718290002, 1, 0, 40.66732, -73.89294], [140160, 1693761933, 1, 5, 40.667824, -73.91298], [140174, 1693919903, 1, 5, 40.94812, -73.89068], [140180, 1723489539, 1, 5, 40.666958, -73.95314], [140186, 1694903405, 1, 1, 40.65198, -74.0098], [140326, 1735091850, 1, 4, 40.625, -73.9655], [140330, 1694905942, 1, 5, 40.674942, -73.93918], [140334, 1774201622, 1, 5, 40.685436, -73.98876], [140332, 1774201590, 1, 5, 40.6468, -73.89742], [140352, 1721254956, 1, 5, 40.75008, -74.00204], [140358, 1693860473, 1, 5, 40.67537, -73.92338], [140362, 1692710986, 1, 1, 40.65159, -73.933044], [140364, 1772969925, 1, 5, 40.644337, -73.928375], [140370, 1683861819, 1, 5, 40.82908, -73.91791], [140368, 1685988350, 1, 5, 40.667072, -73.95768], [140378, 1774201709, 1, 5, 40.865273, -73.90739], [140376, 1679949906, 1, 5, 40.78916, -73.94542], [140380, 1700890338, 1, 5, 40.797993, -73.95169], [140386, 1774201696, 1, 5, 40.641953, -73.92743], [140384, 1671553345, 1, 5, 40.879837, -73.900215], [140392, 1701104870, 1, 5, 40.86178, -73.90797], [140398, 1639516757, 1, 0, 40.666992, -73.957596], [142914, 1683055666, 0, 5, 40.694447, -73.966156], [143784, 1774201621, 1, 0, 40.685123, -73.97788], [144554, 1774201669, 0, 5, 40.694927, -73.97224], [144714, 1765679525, 0, 5, 40.783054, -73.97376], [145962, 1774201628, 0, 5, 40.680958, -74.01284], [145980, 1698782955, 0, 5, 40.68231, -74.006615], [146382, 1675697298, 0, 5, 40.67768, -74.01269], [146442, 1711117010, 0, 5, 40.674248, -74.00646], [146444, 1677909549, 0, 5, 40.682102, -74.00718], [146520, 1706908000, 0, 5, 40.677467, -74.01274], [146960, 1694011012, 0, 5, 40.89742, -73.91381], [147661, 1726100448, 0, 5, 40.72222, -73.9496], [147789, 1764427260, 1, 1, 40.740993, -73.95066], [148359, 1714309234, 0, 5, 40.725967, -73.950714], [148615, 1744048982, 1, 5, 40.592, -73.78877], [148627, 1696583708, 1, 5, 40.8153, -73.95033], [149776, 1674852798, 1, 5, 40.7844, -73.97836], [149796, 1676651741, 1, 5, 40.78471, -73.97756], [150114, 1711136275, 0, 5, 40.727665, -73.958786], [150638, 1663851155, 0, 5, 40.721165, -74.19258], [150696, 1774201647, 0, 5, 40.73411, -73.950005], [151246, 1656365050, 1, 0, 40.810127, -73.96346], [151260, 1659012497, 1, 5, 40.810127, -73.963455], [151270, 1715269772, 0, 5, 40.742165, -73.99637], [151394, 1663851090, 0, 5, 40.721138, -74.192795], [151738, 1668015783, 0, 0, 40.65011, -74.18333], [151740, 1656535671, 0, 0, 40.72108, -74.192604], [151818, 1657030606, 0, 0, 40.720966, -74.19269], [151856, 1661205462, 1, 3, 40.77986, -73.94772], [152194, 1657046663, 0, 0, 40.721237, -74.19287], [152198, 1689693693, 0, 0, 40.72124, -74.19266], [152196, 1774201616, 0, 5, 40.64598, -74.190155], [152202, 1690763820, 0, 5, 40.653633, -74.183334], [152200, 1675875815, 0, 0, 40.721123, -74.19338], [152204, 1707231418, 0, 5, 40.72842, -73.940605], [152236, 1663849709, 0, 5, 40.721264, -74.19263], [152242, 1663851091, 0, 5, 40.721115, -74.19324], [152862, 1774201706, 0, 5, 40.67681, -74.00462], [152894, 1774201604, 0, 5, 40.815487, -73.95053], [154383, 1681747205, 0, 5, 40.717285, -73.96156], [154823, 1774201682, 1, 5, 40.669395, -73.97893], [155309, 1774201654, 1, 5, 40.66952, -73.97924], [155323, 1774201638, 1, 5, 40.669632, -73.979126], [155343, 1774201674, 1, 5, 40.66899, -73.97856], [155349, 1667999360, 0, 0, 40.64584, -73.957245], [157447, 1659386256, 0, 0, 40.734837, -73.82274], [158931, 1708627922, 0, 0, 40.773983, -73.94621], [158939, 1708627799, 0, 0, 40.773987, -73.94614], [158957, 1743724438, 0, 0, 40.774075, -73.946365], [158987, 1680543649, 0, 0, 40.73853, -73.823906], [158989, 1712277790, 0, 2, 40.774162, -73.94632], [158995, 1712183446, 0, 1, 40.774124, -73.94618], [158993, 1675719976, 0, 3, 40.73853, -73.823906], [159361, 1774201654, 0, 5, 40.736748, -73.82209], [161189, 1723477730, 0, 5, 40.76102, -73.987366], [162479, 1734644573, 0, 0, 40.738728, -73.97892], [162519, 1717714853, 1, 5, 40.715782, -73.96677], [163783, 1668015559, 1, 5, 40.718513, -73.94724], [164157, 1763387338, 1, 5, 40.723858, -73.9801], [165199, 1741209059, 0, 5, 40.679283, -74.012146], [165783, 1774201651, 0, 5, 40.67223, -74.01005], [168581, 1722552822, 1, 4, 40.68475, -73.99342], [169657, 1765925441, 0, 5, 40.716137, -73.99831], [170145, 1688159905, 1, 5, 40.776196, -73.95584], [170211, 1716471515, 1, 5, 40.76921, -73.98517], [170209, 1774201594, 1, 5, 40.901546, -73.90176], [170245, 1756927236, 1, 5, 40.7198, -73.96005], [170281, 1774201706, 1, 5, 40.765965, -73.927826], [170487, 1716389735, 1, 5, 40.83379, -73.90273], [170629, 1774201603, 1, 5, 40.72579, -73.942], [170725, 1774201640, 1, 5, 40.726025, -73.93982], [170983, 1774201601, 1, 5, 40.621696, -74.034035], [171265, 1770995850, 1, 3, 40.757935, -73.708046], [171481, 1756661960, 1, 5, 40.897774, -74.02789], [172111, 1774201710, 0, 5, 40.833763, -73.902565], [172109, 1676553351, 1, 5, 40.83378, -73.90275], [172743, 1712852815, 0, 5, 40.717377, -74

In [3]:
raw_sensors_df = pl.DataFrame(data = sensors_json["data"], \
                  schema = sensors_json["fields"])

print(raw_sensors_df.height)
raw_sensors_df.head()

595

C:\Users\crist\AppData\Local\Temp\ipykernel_34068\315921795.py:1: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  raw_sensors_df = pl.DataFrame(data = sensors_json["data"], \

shape: (5, 6)
┌──────────────┬────────────┬───────────────┬─────────────────┬───────────┬────────────┐
│ sensor_index ┆ last_seen  ┆ location_type ┆ position_rating ┆ latitude  ┆ longitude  │
│ ---          ┆ ---        ┆ ---           ┆ ---             ┆ ---       ┆ ---        │
│ i64          ┆ i64        ┆ i64           ┆ i64             ┆ f64       ┆ f64        │
╞══════════════╪════════════╪═══════════════╪═════════════════╪═══════════╪════════════╡
│ 262999       ┆ 1774201640 ┆ 1             ┆ 0               ┆ 40.801434 ┆ -73.970535 │
│ 263287       ┆ 1755525360 ┆ 1             ┆ 5               ┆ 40.842293 ┆ -74.07955  │
│ 263301       ┆ 1755525237 ┆ 1             ┆ 5               ┆ 40.842327 ┆ -74.079544 │
│ 263457       ┆ 1755525786 ┆ 1             ┆ 5               ┆ 40.84218  ┆ -74.07933  │
│ 1660         ┆ 1663947634 ┆ 0             ┆ 5               ┆ 40.721    ┆ -74.1928   │
└──────────────┴────────────┴───────────────┴─────────────────┴───────────┴────────────┘

### Cleaning data

Since we are looking to create a dashboard that shows air quality in NYC, we need to firstly clean the data and do a spatial join to get sensors only within the 5 boroughs,
and also remove the sensors which are in indoors (location_type = 1) and those with a position rating of 0 (position_rating = 0) since they are likely to be inaccurate. We will also convert the last_seen column to a datetime format.

In [9]:
import geopandas as gpd

raw_sensors_gdf = gpd.GeoDataFrame(
                    raw_sensors_df.to_pandas(),
                    geometry=gpd.points_from_xy(raw_sensors_df["longitude"], raw_sensors_df["latitude"]),
                    crs="EPSG:4326"
                )

raw_sensors_gdf = raw_sensors_gdf.loc[(raw_sensors_gdf["position_rating"] > 0) & (raw_sensors_gdf["location_type"] != 1)]

raw_sensors_gdf.head()

,sensor_index,last_seen,location_type,position_rating,latitude,longitude,geometry
4,1660,1663947634,0,5,40.721000,-74.192800,POINT (-74.1928 40.721)
5,2319,1666785882,0,5,40.809963,-73.954160,POINT (-73.95416 40.80996)
7,2897,1518323822,0,5,40.790447,-73.733284,POINT (-73.73328 40.79045)
10,4803,1774201661,0,5,40.787937,-73.968070,POINT (-73.96807 40.78794)
15,5648,1555619294,0,5,40.735424,-74.009460,POINT (-74.00946 40.73542)

In [25]:
# Now that the data is in a geodataframe, we can do a spatial join to remove sensors outside of the 5 boroughs of NYC.
# The borough boundaries data is in the NYC Open Data portal.

response = httpx.get("https://data.cityofnewyork.us/resource/gthc-hcne.geojson")
response.raise_for_status()

geojson = response.json()

boroughs_gdf = gpd.GeoDataFrame.from_features(geojson["features"], crs="EPSG:4326")
boroughs_gdf.head()

,geometry,borocode,boroname,shape_area,shape_leng
0,"MULTIPOLYGON (((-74.05051 40.56642, -74.05047 ...",5,Staten Island,1623618358.46,325912.288988
1,"MULTIPOLYGON (((-74.01093 40.68449, -74.01193 ...",1,Manhattan,636631650.451,359537.866079
2,"MULTIPOLYGON (((-73.89681 40.79581, -73.89694 ...",2,Bronx,1187199300.36,463147.071867
3,"MULTIPOLYGON (((-73.86327 40.58388, -73.86381 ...",3,Brooklyn,1934462607.43,726953.044632
4,"MULTIPOLYGON (((-73.82645 40.59053, -73.82642 ...",4,Queens,3041419178.99,887905.076018